import { Doctor } from './types';

export const mockDoctors: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Prakash Das',
    specialization: 'Cardiologist',
    experience: '15+ years',
    rating: 4.8,
    reviews: 4943,
    patients: '5,000+',
    image: '/doctors/doctor1.svg',
    availability: '09:00 AM to 05:00 PM',
    availableDays: 'Monday to Friday',
    about:
      '15+ years of experience in all aspects of cardiology, including non-invasive and interventional. Interventional procedures.',
    services: ['Service', 'Medicare', 'Cardiology', 'Specialization'],
    education: 'MBBS, MD (Cardiology)',
  },
  {
    id: '2',
    name: 'Dr. Kumar Das',
    specialization: 'Ophthalmologist',
    experience: '10+ years',
    rating: 4.6,
    reviews: 3210,
    patients: '3,000+',
    image: '/doctors/doctor2.svg',
    availability: '10:00 AM to 06:00 PM',
    availableDays: 'Monday to Saturday',
    about:
      '10+ years of experience specializing in comprehensive eye care, cataract surgery, and retinal disorders.',
    services: ['Eye Care', 'Cataract Surgery', 'Retinal Treatment', 'LASIK'],
    education: 'MBBS, MS (Ophthalmology)',
  },
  {
    id: '3',
    name: 'Dr. Kumar Das',
    specialization: 'Cardiologist',
    experience: '12+ years',
    rating: 4.9,
    reviews: 5120,
    patients: '6,000+',
    image: '/doctors/doctor3.svg',
    availability: '08:00 AM to 04:00 PM',
    availableDays: 'Monday to Friday',
    about:
      'Expert in diagnosing and treating heart conditions with a specialization in cardiac interventions and preventive cardiology.',
    services: ['Cardiac Surgery', 'ECG', 'Echocardiogram', 'Stress Testing'],
    education: 'MBBS, MD (Internal Medicine)',
  },
  {
    id: '4',
    name: 'Dr. Ananya Sharma',
    specialization: 'Dermatologist',
    experience: '8+ years',
    rating: 4.7,
    reviews: 2840,
    patients: '4,200+',
    image: '/doctors/doctor4.svg',
    availability: '09:00 AM to 05:00 PM',
    availableDays: 'Monday to Friday',
    about:
      'Experienced dermatologist specializing in skin diseases, cosmetic dermatology, and laser treatments.',
    services: ['Skin Care', 'Acne Treatment', 'Laser Therapy', 'Cosmetic Dermatology'],
    education: 'MBBS, MD (Dermatology)',
  },
  {
    id: '5',
    name: 'Dr. Rajesh Gupta',
    specialization: 'Neurologist',
    experience: '20+ years',
    rating: 4.9,
    reviews: 6200,
    patients: '8,000+',
    image: '/doctors/doctor5.svg',
    availability: '10:00 AM to 04:00 PM',
    availableDays: 'Monday to Thursday',
    about:
      'Renowned neurologist with expertise in stroke management, epilepsy treatment, and neurodegenerative disorders.',
    services: ['Neurology Consult', 'EEG', 'Stroke Management', 'Epilepsy Treatment'],
    education: 'MBBS, DM (Neurology)',
  },
  {
    id: '6',
    name: 'Dr. Sneha Patel',
    specialization: 'Pediatrician',
    experience: '12+ years',
    rating: 4.8,
    reviews: 4100,
    patients: '5,500+',
    image: '/doctors/doctor6.svg',
    availability: '09:00 AM to 06:00 PM',
    availableDays: 'Monday to Saturday',
    about:
      'Dedicated pediatrician providing comprehensive childcare services including immunization, growth monitoring, and childhood illness management.',
    services: ['Child Care', 'Vaccination', 'Growth Monitoring', 'Newborn Care'],
    education: 'MBBS, MD (Pediatrics)',
  },
  {
    id: '7',
    name: 'Dr. Vikram Singh',
    specialization: 'Orthopedic',
    experience: '14+ years',
    rating: 4.7,
    reviews: 3650,
    patients: '4,800+',
    image: '/doctors/doctor7.svg',
    availability: '08:00 AM to 03:00 PM',
    availableDays: 'Monday to Friday',
    about:
      'Orthopedic surgeon specializing in joint replacements, sports injuries, and spinal surgeries.',
    services: ['Joint Replacement', 'Sports Medicine', 'Spine Surgery', 'Fracture Treatment'],
    education: 'MBBS, MS (Orthopedics)',
  },
  {
    id: '8',
    name: 'Dr. Meera Joshi',
    specialization: 'Psychiatrist',
    experience: '10+ years',
    rating: 4.6,
    reviews: 2680,
    patients: '3,500+',
    image: '/doctors/doctor8.png',
    availability: '10:00 AM to 05:00 PM',
    availableDays: 'Monday to Friday',
    about:
      'Compassionate psychiatrist with expertise in anxiety, depression, bipolar disorder, and stress management.',
    services: ['Counseling', 'CBT', 'Medication Management', 'Anxiety Treatment'],
    education: 'MBBS, MD (Psychiatry)',
  },
];
